name: cc4real
favicon: null
layout_spectrum: 0
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3c0000'
    - '#720000'
    - '#a20000'
    - '#f70000'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.9725460805930197
purpose: []
